---
services:
  call-congress-api:
    git_url: git@github.com:PurposeOpen/call-congress.git
    git_branch: master
    ports:
    - container: 5000
      http: 80
      https: 443
    command: python app.py
    env_vars:
      TWILIO_ACCOUNT_SID:
      TWILIO_AUTH_TOKEN:
      APPLICATION_ROOT: http://dockerhost.call-congress.c66.me
databases:
  - postgresql

